# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb7b73dbd7b89a63ed1df3c1fd77e7f6a53db104a8713b0015018b2b559f0d0d8f69a8615fde134a5e0807a54983b09771242e406293fd516ef40addf2e4a21

test:
  secret_key_base: c7e1871d741e4d369881084330062d4c5d92e2ec23af8783e21f429a49ca0786243ef327b1f2971fd6464b4bea68c0c1f88cf328c7d49448948e4b823581fc41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
